config/routes.rb
Rails.application.routes.draw do 

	root "home#index"

	namespace :admin do
		resource :dashboard, only: [:show]
		resources :products
	end

	
  resource :about, only: [:show]
	resources :products
	resources :sellers
	resources :categories
	resources :users, only: [:new, :create, :show]
	resource :session, only: [:new, :create, :destroy]
end

app/models/seller.rb
class Seller < ApplicationRecord
	has_many :products, dependent: :destroy
	
	validates_presence_of :name, :rating
	validates :rating, numericality: true
	validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

before_action :authorize, { only: [:new, :update, :destroy, :edit] }
before_action :find_seller, { only: [:edit, :update, :show, :destroy] }

	def index
		@sellers = Seller.all
	end

  def new
		@seller = Seller.new
	end

	def create
		@seller = Seller.new(seller_params)

		if @seller.save
			flash[:notice] = 'Seller created succesfully :)'
			redirect_to sellers_path
		else
			render :new
		end

	end

	def edit
			
	end

	def update		
	  
		if @seller.update(seller_params)
			redirect_to @seller
		else
			render :edit
		end
	end

	def show    
    @products = @seller.products
  end

	def destroy
	
		@seller.destroy
		flash[:notice] = 'Seller deleted succesfully'
		redirect_to sellers_path
	end

	private 
	def seller_params
		params.require(:seller).permit(:name, :rating);
	end
  
  def find_seller
		@seller = Seller.find(params[:id])
	end

 end

app/views/sellers/_back.html.erb
<div class="panel panel-primary">
  <div class="panel-body">
    <%= link_to 'Back to sellers', sellers_path %>
  </div>
</div>

app/views/sellers/_form.html.erb
<%= form_for @seller do |form|%>	
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <br>
  <%= form.label :rating %>
  <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
  <%= form.text_field :rating, class: 'form-control' %>
  <br>  
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/sellers/_products.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Products <span class="badge"><%= @products.count %></span>
	</div>  
  	<table class="table table-striped table-hover">
  		<thead>
				<tr>
	    		<th>Name</th>
	    		<th>Price</th>
	    		<th>Category</th>
	    		<th>Created at</th>
	    		<th>Actions</th>
				</tr>
			</thead>
			<tbody>
    		<% @products.each do |product| %>
					<tr>
						<td><%= link_to product.name, product_path(product) %></td>	
						<td><%= product.price %></td>		
						<td><%= link_to product.category.name, category_path(product.category_id) %></td>
						<td><%= product.created_at.strftime("%Y-%d-%m") %></td>
						<td><%= link_to ' Edit', edit_product_path(product), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
						<%= link_to ' Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
					</tr>
				<% end %>
			</tbody>
  	</table>
</div>

app/views/sellers/_seller.html.erb
<tr>
	<td><%= link_to seller.name, seller_path(seller) %></td>	
	<td><%= seller.rating %></td>	
	<td><%= link_to ' Edit', edit_seller_path(seller), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', seller_path(seller), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
</tr>

app/views/sellers/edit.html.erb
<% provide(:title, "Edit Seller") %>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">   
  	<div class="well well-sm"><h1 style="text-align: center";>Update seller</h1>
  
	  <%= render 'shared/validation_messages', model: @seller %>
	  <%= render 'form' %>

	  </div>
	  <%= render 'back' %>
  </div>
</div>

app/views/sellers/index.html.erb
<% provide(:title, "Sellers") %>
<div class="row col-md-5">
	<div class="well well-sm"><h3>Sellers <%= link_to 'Add new', new_seller_path, class: 'btn btn-sm btn-primary' %></h3>
		<%= count_for @sellers%>
		<% unless flash[:notice].blank? %>
		<div class="alert alert-success">
			<p><%= flash[:notice] %></p>
		</div>
		<% end %>
  </div>
  
  <div class="panel panel-default">  
  	<div class="panel-heading"><strong>Seller details</strong></div>  
  		<table class="table table-hover table-striped">	
				<thead>
					<tr>
		    		<th>Name</th>
		    		<th>Rating</th>
		    		<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<%= render @sellers.order(rating: :desc) %>
				</tbody>
			</table>
</div>




	

app/views/sellers/new.html.erb
<% provide(:title, "Add New Seller") %>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
  	<div class="well well-sm";><h1 style="text-align: center">Add new seller</h1>

   	<%= render 'shared/validation_messages', model: @seller %>
    <%= render 'form' %>

    </div>
    
    <%= render 'back' %>

  </div>
</div>

app/views/sellers/show.html.erb
<% provide(:title, "Seller Details") %>
<div class="row col-md-5 col-md-offset-3">
	<div class="panel panel-primary" style="width: 100%">
  	<div class="panel-heading">
    	<h3 class="panel-title">Name</h3>
  	</div>
  	<div class="panel-body">
    	<%= @seller.name %>
  	</div>
  	<div class="panel-heading">
    	<h3 class="panel-title">Rating</h3>
  	</div>
  	<div class="panel-body">
      <strong><%= render_stars @seller.rating %> </strong>
  	</div>
	</div>
</div>

<div class="row col-md-9 col-md-offset-1">

	<%= render 'products' %>
  <%= render 'back' %>
	
</div>