config/routes.rb
Rails.application.routes.draw do 

	root "home#index"

	namespace :admin do
		resource :dashboard, only: [:show]
		resources :products
	end

	
  resource :about, only: [:show]
	resources :products
	resources :sellers
	resources :categories
	resources :users, only: [:new, :create, :show]
	resource :session, only: [:new, :create, :destroy]
end

app/views/shared/_bootstrap.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to 'RoR3 Web Shop', root_path %> by <a href="https://www.facebook.com/jusmir.husejnovic">Jusmir Husejnović</a>
  </small>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
<%= link_to image_tag("ror3-shop-logo.png", alt: "RoR Web Shop", id: "logo" ), root_path %>

  <ul class="nav navbar-nav">
  	<li class="<%= 'active' if controller?('home') %>"><%= link_to 'Home', root_path %></li>  		
 		<li class="<%= 'active' if controller?('products') %>"><%= link_to 'Products', products_path %></li>
 		<li class="<%= 'active' if controller?('sellers') %>"><%= link_to 'Sellers', sellers_path %></li>
    <li class="<%= 'active' if controller?('categories') %>"><%= link_to 'Categories', categories_path %></li>
    <li class="<%= 'active' if controller?('abouts') %>"><%= link_to 'About', about_path%></li>
  </ul>
 </nav>

app/views/shared/_validation_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
   	<% model.errors.full_messages.each do |error| %>
   	<p><%= error %></p>
   	<% end %>
  </div>
<% end %>