config/routes.rb
Rails.application.routes.draw do 

	root "home#index"

	namespace :admin do
		resource :dashboard, only: [:show]
		resources :products
	end

	
  resource :about, only: [:show]
	resources :products
	resources :sellers
	resources :categories
	resources :users, only: [:new, :create, :show]
	resource :session, only: [:new, :create, :destroy]
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :seller
	belongs_to :category

	validates_presence_of :name, :price
	validates :name, length: { in: 4..30 }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController	

before_action :find_product, { only: [:edit, :update, :show, :destroy] }

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			flash[:notice] = 'Product created succesfully :)'
			redirect_to [:admin, @product]
		else
			render :new
		end

	end

	def edit
   
	end

	def update
			
		if @product.update(product_params)
			redirect_to [:admin, @product]
		else
			render :edit
		end
	end

	def show
			
	end

	def destroy

		@product.destroy
		flash[:notice] = 'Product deleted succesfully'
		redirect_to admin_products_path
	end

	private 
	def product_params
		params.require(:product).permit(:name, :price, :category_id, :description, :seller_id);
	end

	def find_product
		@product = Product.find(params[:id])
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController	
	before_action :find_product, { only: [:edit, :update, :show, :destroy] }

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			flash[:notice] = 'Product created succesfully :)'
			redirect_to products_path
		else
			render :new
		end

	end

	def edit
   
	end

	def update
			
		if @product.update(product_params)
			render :show
		else
			render :edit
		end
	end

	def show
			
	end

	def destroy

		@product.destroy
		flash[:notice] = 'Product deleted succesfully'
		redirect_to products_path
	end

	private 
	def product_params
		params.require(:product).permit(:name, :price, :category_id, :description, :seller_id);
	end

	def find_product
		@product = Product.find(params[:id])
	end
end

app/views/admin/products/_back.html.erb
<div class="panel panel-primary">
  <div class="panel-body">
    <%= link_to 'Back to products', admin_products_path %>
  </div>
</div>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |form|%>	
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <%= error_for :name, @product.errors do |message| %>
  <strong><%= message %></strong>
  <% end %>
  <br>
  <%= form.label :price %>
  <div class="input-group">
    <span class="input-group-addon">$</span>
    <%= form.text_field :price, class: 'form-control' %>
  </div>   	
    	<%= error_for :price, @product.errors %>
  <br>
  <%= form.label :category_id %>
  <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: 'Choose category'}, class: 'form-control' %>
  <%= error_for :category, @product.errors %>
  <br>
  <%= form.label :description, 'Description (optional)' %>
  <%= form.text_area :description, class: 'form-control' %>
  <%= error_for :description, @product.errors %>
  <br>
  <%= form.label :seller_id %>
  <%= form.collection_select :seller_id, Seller.all, :id, :name, { prompt: 'Choose seller'}, class: 'form-control' %>
  <%= error_for :seller, @product.errors %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
	<td><%= link_to product.name, product_path(product) %></td>	
	<td><%= product.price %></td>	
	<td><%= link_to product.seller.name, seller_path(product.seller_id) %></td>
	<td><%= link_to product.category.name, category_path(product.category_id) %></td>
	<td><%= product.created_at.strftime("%Y-%d-%m") %></td>
	<td><%= link_to ' Edit', edit_product_path(product), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
			<%= link_to ' Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
</tr>

app/views/admin/products/index.html.erb
<% provide(:title, "Products") %>

<div class="row col-md-9">
	<div class="well well-sm"><h3>Products <%= link_to 'Add new', new_product_path, class: 'btn btn-sm btn-primary' %></h3>
	<%= count_for @products%>
	<% unless flash[:notice].blank? %>
		<div class="alert alert-success">
			<p><%= flash[:notice] %></p>
		</div>
	<% end %>	
	</div>  
	

<div class="panel panel-default">  
  <div class="panel-heading"><strong>Product details</strong></div>
  	<table class="table table-hover table-striped">	
			<thead>
				<tr>
	    		<th>Name</th>
	    		<th>Price</th>
	    		<th>Seller</th>
	    		<th>Category</th>
	    		<th>Created at</th>
	    		<th>Actions</th>
				</tr>
			</thead>

			<tbody>
				<%= render @products.order(price: :desc) %>
			</tbody>
		</table>
</div>

app/views/admin/products/new.html.erb
<% provide(:title, "Add New Product") %>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
  	<div class="well well-sm"><h1 style="text-align: center";>Add new product</h1>  

   	<%= render 'shared/validation_messages', model: @product %>
   	<%= render 'form' %>

    </div>
    <%= render 'back' %>
  </div>
</div>

app/views/admin/products/show.html.erb
<% provide(:title, "Product Details") %>
<div class="row col-md-9 col-md-offset-1">
  <div class="panel panel-primary">
  	<div class="panel-heading">
    	<h3 class="panel-title">Name</h3>
  	</div>
  	<div class="panel-body">
    	<%= @product.name %>
  	</div>
  	<div class="panel-heading">
    	<h3 class="panel-title">Price</h3>
  	</div>
  	<div class="panel-body">
    	<%= @product.price %>
  	</div>
  	<div class="panel-heading">
    	<h3 class="panel-title">Description</h3>
  	</div>
  	<div class="panel-body">
    	<%= @product.description %>
  	</div>
	</div>	

	<%= render 'back' %>
</div>