config/routes.rb
Rails.application.routes.draw do 

	root "home#index"

	namespace :admin do
		resource :dashboard, only: [:show]
		resources :products
	end

	
  resource :about, only: [:show]
	resources :products
	resources :sellers
	resources :categories
	resources :users, only: [:new, :create, :show]
	resource :session, only: [:new, :create, :destroy]
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	
	validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	before_action :authorize, { only: [:new, :update, :destroy, :edit] }
	before_action :find_category, { only: [:edit, :update, :show, :destroy] }
	
	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

  def create
		@category = Category.new(product_params)

		if @category.save
			flash[:notice] = 'Category created succesfully :)'
			redirect_to categories_path
		else
			render :new
		end

	end

	def edit
		
	end

	def update
			
		if @category.update(product_params)
			redirect_to @category
		else
			render :edit
		end
	end

	def show
	  @products = @category.products
	end

	def destroy

		@category.destroy
		flash[:notice] = 'Category deleted succesfully'
		redirect_to categories_path
	end

	private 
	def product_params
		params.require(:category).permit(:name, :description);
	end

def find_category
@category = Category.find(params[:id])
end


end

app/views/categories/_back.html.erb
<div class="panel panel-primary">
  <div class="panel-body">
    <%= link_to 'Back to categories', categories_path %>
  </div>
</div>

app/views/categories/_category.html.erb
<% @categories.each do |category| %>
	<tr>
		<td><%= link_to category.name, category_path(category) %></td>	
		<td><%= link_to ' Edit', edit_category_path(category), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
				<%= link_to ' Delete', category_path(category), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %></td>
	</tr>
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |form|%>	
  <%= form.label :name %>
  <%= form.text_field :name, autofocus: :true, class: 'form-control' %>
  <%= error_for :name, @category.errors do |message| %>
  <strong><%= message %></strong>
  <% end %>
  <br>
  <%= form.label :description, 'Description (optional)' %>
  <%= form.text_area :description, class: 'form-control' %>
  <%= error_for :description, @category.errors %>
  <br>
  <%= form.submit params[:action] == 'new' ? 'Save' : 'Update', class: 'btn btn-block btn-default' %>
<% end %>

app/views/categories/_products.html.erb
<div class="panel panel-primary">  
  <div class="panel-heading">Products <span class="badge"><%= @products.count %></span>
  </div>      
  <table class = 'table table-striped table-hover'>
    <thead>
			<tr>
    		<th>Name</th>
    		<th>Price</th>
    		<th>Seller</th>
    		<th>Created at</th>
    		<th>Actions</th>
			</tr>
		</thead>
		<tbody>
      <% @products.each do |product| %>
				<tr>
					<td><%= link_to product.name, product_path(product) %></td>	
					<td><%= product.price %></td>		
					<td><%= link_to product.seller.name, seller_path(product.seller_id) %></td>
					<td><%= product.created_at.strftime("%Y-%d-%m") %></td>
					<td><%= link_to ' Edit', edit_product_path(product), class: 'glyphicon glyphicon-edit btn btn-sm btn-primary' %>
							<%= link_to ' Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: 'glyphicon glyphicon-trash btn btn-sm btn-danger' %></td>
				</tr>
			<% end %>
		</tbody>
  </table>
</div>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
  	<div class="well well-sm"><h1 style="text-align: center";>Update category</h1>

    <%= render 'shared/validation_messages', model: @category %>
    <%= render 'form' %>

    </div>
    <%= render 'back' %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, "Categories") %>

<div class="row col-md-6">
	<div class="well well-sm"><h3>Categories <%= link_to 'Add new', new_category_path, class: 'btn btn-sm btn-primary' %> </h3>
	<%= count_for @categories%>
	<% unless flash[:notice].blank? %>
		<div class="alert alert-success">
			<p><%= flash[:notice] %></p>
		</div>
	<% end %>	
	</div>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Category details</strong></div>

  <table class="table table-hover table-striped">	
		<thead>
			<tr>
     		<th>Name</th>
    		<th>Actions</th>
			</tr>
		</thead>

		<tbody>		
		<%= render 'category' %>
		</tbody>
	</table>
</div>

app/views/categories/new.html.erb
<% provide(:title, "Add New Category") %>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4">
  	<div class="well well-sm"><h1 style="text-align: center">Add new category</h1>   	

   	<%= render 'shared/validation_messages', model: @category %>
   	<%= render 'form' %>

   	</div>
   	<%= render 'back' %>
 	</div> 	
</div>

app/views/categories/show.html.erb
<% provide(:title, "Category Details") %>
<div class="row col-md-7 col-md-offset-2">
  <div class="panel panel-primary">
  	<div class="panel-heading">
      <h3 class="panel-title">Name</h3>
  	</div>
  	<div class="panel-body">
    	<%= @category.name %>
  	</div>
    <div class="panel-heading">
    	<h3 class="panel-title">Description</h3>
  	</div>
  	<div class="panel-body">
    	<%= @category.description %>
  	</div>
	</div>
</div>
  <div class="row col-md-9 col-md-offset-1">
	<%= render 'products' %>
	<%= render 'back' %>
  </div>